# Generated by Django 5.0.4 on 2024-05-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='author',
        ),
    ]
