# Generated by Django 5.0.4 on 2024-05-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_mgmt', '0002_remove_customuser_groups'),
        ('task_app', '0005_remove_task_assigned_to_remove_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='auth_mgmt.customuser'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='auth_mgmt.customuser'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='auth_mgmt.customuser'),
            preserve_default=False,
        ),
    ]
