# Generated by Django 5.0.4 on 2024-05-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='content',
            new_name='comment',
        ),
    ]
