# Generated by Django 5.0.4 on 2024-05-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_rename_comment_taskcomment_co_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='co',
            new_name='comment',
        ),
    ]
