# Generated by Django 5.0.4 on 2024-05-07 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_rename_co_taskcomment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Efforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('remind', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('efforts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_app.efforts')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task')),
            ],
        ),
    ]
