# Generated by Django 5.0.4 on 2024-05-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_efforts_employeeassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='efforts',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_app.task'),
            preserve_default=False,
        ),
    ]
