# Generated by Django 5.0.4 on 2024-05-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_task_dependencies_task_parent_task_collaboration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='user',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='activity_log',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='task_app.task'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='task_app.label'),
        ),
    ]
