# Generated by Django 5.0.4 on 2024-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_remove_usersettings_language_usersettings_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Bug Fix', 'Bug Fix'), ('Design Review', 'Design Review')], max_length=50, unique=True),
        ),
    ]
