# Generated by Django 5.0.4 on 2024-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0017_alter_label_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='labels',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Bug Fix', 'Bug Fix'), ('Design Review', 'Design Review')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
